name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps: 
      - name: 🚚 Get latest code
        uses: actions/checkout@main
      - name: 📂 Sync files
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ftpupload.net
          user: epiz_30046706
          password: ${{secrets.FTP_PASSWORD}}
          local_dir: "./htdocs"
          remote_dir: "./htdocs"
          delete: "false"
