name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps: 
      - name: 🚚 Get latest code
        uses: actions/checkout@main
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftpupload.net
          username: epiz_30046706
          password: ${{secrets.FTP_PASSWORD}}
